### ISSUE TITLE
Syntax for remotes where repo name / file name if different from package name.

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/depends#2]
cc @jimhester 

To make dependency resolution easier. 

We could put the optional package name to the front or the end of the string, maybe front is better. We also need a new separator for it. How about a single `:`? If there is no `:` then the package name must match the repo name or file name (for `url` or `local` remotes).

```
package:user/repo
package:github::user/repo
package:url::https://xy.com/filename_1.0.0.tar.gz
```

Another alternative to `:` is `=`. We could also change the order of the remote type and the package name, I don't mind:
```
package:user/repo
github::package:user/repo
url::package:https://xy.com/filename_1.0.0.tar.gz
```

It does not look very good, but this syntax should be rarely needed, anyway.

This is the current GitHub remote syntax: 
```r
    github = paste0(
      "^",
      ## Optional remote type
      "(?:github::)?",
      ## Username
      "(?<username>(?:[^/]+))/",
      ## Repo
      "(?<repo>[^/@#]+)",
      ## Subdirectory
      "(?:/(?<subdir>(?:[^@#]*[^@#/])/?))?",
      ## Commit / PR / Release
      github_detail,
      "$"
    )
```

where

```r
  github_commitish_rx <- "(?:@(?<commitish>[^*].*))"
  github_pull_rx <- "(?:#(?<pull>[0-9]+))"
  github_release_rx <- "(?:@(?<release>[*]release))"
  github_detail <- sprintf(
    "(?:(?:%s)|(?:%s)|(?:%s))?",
    github_commitish_rx,
    github_pull_rx,
    github_release_rx
  )
```

**Comment by jimhester** [comment]
`package=user/repo` seems like the best option to me

**Comment by gaborcsardi** [comment]
Would you put `package=` in the front, or `github::`. Maybe `github::` is better, then we can easily parse the type and potentially give it to a plugin.

**Comment by gaborcsardi** [comment]
But I don't have a strong opinion either way.

**Comment by gaborcsardi** [comment]
Also, should we allow it for every remote type? For some, e.g. CRAN or BioC, it is not really needed. I am just thinking if I should include it in the CRAN regex. Or maybe we can have a meta-regex, that is just for `[type::]?[package=]?ref`.

**Comment by gaborcsardi** [comment]
`pkg=github::user/repo` looks better than `github::pkg=user/repo`
